CREATE TABLE almanac_daily(date_id text, symbol text,
gl_percent_5 decimal,  accuracy_range_5 decimal, sd_5 decimal,
gl_percent_6 decimal,  accuracy_range_6 decimal, sd_6 decimal,
gl_percent_7 decimal,  accuracy_range_7 decimal, sd_7 decimal,
gl_percent_8 decimal,  accuracy_range_8 decimal, sd_8 decimal,
gl_percent_9 decimal,  accuracy_range_9 decimal, sd_9 decimal,
gl_percent_10 decimal, accuracy_range_10 decimal,sd_10 decimal,
gl_percent_11 decimal, accuracy_range_11 decimal,sd_11 decimal,
gl_percent_12 decimal, accuracy_range_12 decimal,sd_12 decimal,
gl_percent_13 decimal, accuracy_range_13 decimal,sd_13 decimal,
gl_percent_14 decimal, accuracy_range_14 decimal,sd_14 decimal,
gl_percent_15 decimal, accuracy_range_15 decimal,sd_15 decimal,
gl_percent_16 decimal, accuracy_range_16 decimal,sd_16 decimal,
gl_percent_17 decimal, accuracy_range_17 decimal,sd_17 decimal,
gl_percent_18 decimal, accuracy_range_18 decimal,sd_18 decimal,
gl_percent_19 decimal, accuracy_range_19 decimal,sd_19 decimal,
gl_percent_20 decimal, accuracy_range_20 decimal,sd_20 decimal,
gl_percent_21 decimal, accuracy_range_21 decimal,sd_21 decimal,
gl_percent_22 decimal, accuracy_range_22 decimal,sd_22 decimal,
gl_percent_23 decimal, accuracy_range_23 decimal,sd_23 decimal,
gl_percent_24 decimal, accuracy_range_24 decimal,sd_24 decimal,
gl_percent_25 decimal, accuracy_range_25 decimal,sd_25 decimal,
gl_percent_26 decimal, accuracy_range_26 decimal,sd_26 decimal,
gl_percent_27 decimal, accuracy_range_27 decimal,sd_27 decimal,
gl_percent_28 decimal, accuracy_range_28 decimal,sd_28 decimal,
gl_percent_29 decimal, accuracy_range_29 decimal,sd_29 decimal,
gl_percent_30 decimal, accuracy_range_30 decimal,sd_30 decimal,
gl_percent_31 decimal, accuracy_range_31 decimal,sd_31 decimal,
gl_percent_32 decimal, accuracy_range_32 decimal,sd_32 decimal,
gl_percent_33 decimal, accuracy_range_33 decimal,sd_33 decimal,
gl_percent_34 decimal, accuracy_range_34 decimal,sd_34 decimal,
gl_percent_35 decimal, accuracy_range_35 decimal,sd_35 decimal,
gl_percent_36 decimal, accuracy_range_36 decimal,sd_36 decimal,
gl_percent_37 decimal, accuracy_range_37 decimal,sd_37 decimal,
gl_percent_38 decimal, accuracy_range_38 decimal,sd_38 decimal,
gl_percent_39 decimal, accuracy_range_39 decimal,sd_39 decimal,
gl_percent_40 decimal, accuracy_range_40 decimal,sd_40 decimal,
gl_percent_41 decimal, accuracy_range_41 decimal,sd_41 decimal,
gl_percent_42 decimal, accuracy_range_42 decimal,sd_42 decimal,
gl_percent_43 decimal, accuracy_range_43 decimal,sd_43 decimal,
gl_percent_44 decimal, accuracy_range_44 decimal,sd_44 decimal,
gl_percent_45 decimal, accuracy_range_45 decimal,sd_45 decimal,
gl_percent_46 decimal, accuracy_range_46 decimal,sd_46 decimal,
gl_percent_47 decimal, accuracy_range_47 decimal,sd_47 decimal,
gl_percent_48 decimal, accuracy_range_48 decimal,sd_48 decimal,
gl_percent_49 decimal, accuracy_range_49 decimal,sd_49 decimal,
gl_percent_50 decimal, accuracy_range_50 decimal,sd_50 decimal,
gl_percent_51 decimal, accuracy_range_51 decimal,sd_51 decimal,
gl_percent_52 decimal, accuracy_range_52 decimal,sd_52 decimal,
gl_percent_53 decimal, accuracy_range_53 decimal,sd_53 decimal,
gl_percent_54 decimal, accuracy_range_54 decimal,sd_54 decimal,
gl_percent_55 decimal, accuracy_range_55 decimal,sd_55 decimal,
gl_percent_56 decimal, accuracy_range_56 decimal,sd_56 decimal,
gl_percent_57 decimal, accuracy_range_57 decimal,sd_57 decimal,
gl_percent_58 decimal, accuracy_range_58 decimal,sd_58 decimal,
gl_percent_59 decimal, accuracy_range_59 decimal,sd_59 decimal,
gl_percent_60 decimal, accuracy_range_60 decimal,sd_60 decimal,
gl_percent_61 decimal, accuracy_range_61 decimal,sd_61 decimal,
gl_percent_62 decimal, accuracy_range_62 decimal,sd_62 decimal,
gl_percent_63 decimal, accuracy_range_63 decimal,sd_63 decimal,
gl_percent_64 decimal, accuracy_range_64 decimal,sd_64 decimal,
gl_percent_65 decimal, accuracy_range_65 decimal,sd_65 decimal,
gl_percent_66 decimal, accuracy_range_66 decimal,sd_66 decimal,
gl_percent_67 decimal, accuracy_range_67 decimal,sd_67 decimal,
gl_percent_68 decimal, accuracy_range_68 decimal,sd_68 decimal,
gl_percent_69 decimal, accuracy_range_69 decimal,sd_69 decimal,
gl_percent_70 decimal, accuracy_range_70 decimal,sd_70 decimal,
gl_percent_71 decimal, accuracy_range_71 decimal,sd_71 decimal,
gl_percent_72 decimal, accuracy_range_72 decimal,sd_72 decimal,
gl_percent_73 decimal, accuracy_range_73 decimal,sd_73 decimal,
gl_percent_74 decimal, accuracy_range_74 decimal,sd_74 decimal,
gl_percent_75 decimal, accuracy_range_75 decimal,sd_75 decimal,
gl_percent_76 decimal, accuracy_range_76 decimal,sd_76 decimal,
gl_percent_77 decimal, accuracy_range_77 decimal,sd_77 decimal,
gl_percent_78 decimal, accuracy_range_78 decimal,sd_78 decimal,
gl_percent_79 decimal, accuracy_range_79 decimal,sd_79 decimal,
gl_percent_80 decimal, accuracy_range_80 decimal,sd_80 decimal,
gl_percent_81 decimal, accuracy_range_81 decimal,sd_81 decimal,
gl_percent_82 decimal, accuracy_range_82 decimal,sd_82 decimal,
gl_percent_83 decimal, accuracy_range_83 decimal,sd_83 decimal,
gl_percent_84 decimal, accuracy_range_84 decimal,sd_84 decimal,
gl_percent_85 decimal, accuracy_range_85 decimal,sd_85 decimal,
gl_percent_86 decimal, accuracy_range_86 decimal,sd_86 decimal,
gl_percent_87 decimal, accuracy_range_87 decimal,sd_87 decimal,
gl_percent_88 decimal, accuracy_range_88 decimal,sd_88 decimal,
gl_percent_89 decimal, accuracy_range_89 decimal,sd_89 decimal,
gl_percent_90 decimal, accuracy_range_90 decimal,sd_90 decimal,
gl_percent_91 decimal, accuracy_range_91 decimal,sd_91 decimal,
gl_percent_92 decimal, accuracy_range_92 decimal,sd_92 decimal,
gl_percent_93 decimal, accuracy_range_93 decimal,sd_93 decimal,
gl_percent_94 decimal, accuracy_range_94 decimal,sd_94 decimal,
gl_percent_95 decimal, accuracy_range_95 decimal,sd_95 decimal,
gl_percent_96 decimal, accuracy_range_96 decimal,sd_96 decimal,
gl_percent_97 decimal, accuracy_range_97 decimal,sd_97 decimal,
gl_percent_98 decimal, accuracy_range_98 decimal,sd_98 decimal,
gl_percent_99 decimal, accuracy_range_99 decimal,sd_99 decimal,
gl_percent_100 decimal, accuracy_range_100 decimal,sd_100 decimal,

PRIMARY KEY (date_id, symbol));


CREATE TABLE almanac_log(
       process text,
       symbol text,
       completed boolean,
       PRIMARY KEY(process, symbol));
